//! The agent registry — `_bmad/config.toml` `[agents.*]` (FR-1).
//!
//! **AD-3: read-only.** This file is regenerated by every `bmad-method install`; waggle's
//! own settings belong in `_bmad/custom/`.
//!
//! **The registry is authoritative for what is a persona agent.** A `customize.toml` with
//! an `[agent]` block is *not* sufficient evidence: `bmad-agent-builder` ships one
//! containing `build_standards` and `evals_required` and no identity fields at all — it is
//! a workflow-shaped skill reusing the key. Enumerating from disk instead of the registry
//! would try to compile it and fail on a missing `name`.

use std::collections::BTreeMap;
use std::path::Path;

use serde::Deserialize;

use crate::MethodError;

/// One registered agent descriptor.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct RegisteredAgent {
    /// Owning module code, e.g. `bmm`.
    pub module: String,
    #[serde(default)]
    pub team: Option<String>,
    /// Human name, e.g. `Mary`.
    pub name: String,
    #[serde(default)]
    pub title: Option<String>,
    #[serde(default)]
    pub icon: Option<String>,
    /// Registry-held description. Not present in `customize.toml`.
    #[serde(default)]
    pub description: Option<String>,
}

#[derive(Debug, Deserialize)]
struct ConfigToml {
    #[serde(default)]
    agents: BTreeMap<String, RegisteredAgent>,
}

/// Read the registry, keyed by agent id, in deterministic order (NFR-1).
pub fn read(project_root: &Path) -> Result<BTreeMap<String, RegisteredAgent>, MethodError> {
    let path = project_root.join("_bmad").join("config.toml");
    if !path.exists() {
        return Err(MethodError::NotInstalled(project_root.to_path_buf(), path));
    }

    let raw = std::fs::read_to_string(&path).map_err(|source| MethodError::Unreadable {
        path: path.clone(),
        source,
    })?;

    let parsed: ConfigToml = toml::from_str(&raw).map_err(|e| MethodError::UnparseableToml {
        path,
        reason: e.to_string(),
    })?;

    Ok(parsed.agents)
}

/// Agent ids for one module, in deterministic order.
pub fn agents_for_module(
    registry: &BTreeMap<String, RegisteredAgent>,
    module: &str,
) -> Vec<String> {
    registry
        .iter()
        .filter(|(_, a)| a.module == module)
        .map(|(id, _)| id.clone())
        .collect()
}

/// Modules that have at least one registered agent, in deterministic order.
pub fn modules(registry: &BTreeMap<String, RegisteredAgent>) -> Vec<String> {
    let mut m: Vec<String> = registry.values().map(|a| a.module.clone()).collect();
    m.sort();
    m.dedup();
    m
}

/// Skill directories carrying an `[agent]` block that the registry does not list.
///
/// Reported rather than compiled (AD-6): these are usually workflow-shaped skills, not
/// personas, and attempting to compile one produces a confusing error about a missing
/// `name` rather than an honest "this is not a persona agent".
pub fn unregistered_agent_blocks(
    project_root: &Path,
    tool_dir: &str,
    registry: &BTreeMap<String, RegisteredAgent>,
) -> Vec<String> {
    let dir = project_root.join(tool_dir);
    let Ok(entries) = std::fs::read_dir(&dir) else {
        return Vec::new();
    };

    let mut out: Vec<String> = entries
        .filter_map(Result::ok)
        .filter_map(|e| {
            let id = e.file_name().to_string_lossy().to_string();
            if registry.contains_key(&id) {
                return None;
            }
            let customize = e.path().join("customize.toml");
            let body = std::fs::read_to_string(customize).ok()?;
            body.contains("[agent]").then_some(id)
        })
        .collect();
    out.sort();
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn repo_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .parent()
            .unwrap()
            .to_path_buf()
    }

    #[test]
    fn reads_the_real_registry() {
        let reg = read(&repo_root()).expect("registry should read");
        assert!(reg.contains_key("bmad-tea"));
        let tea = &reg["bmad-tea"];
        assert_eq!(tea.module, "tea");
        assert_eq!(tea.name, "Murat");
        assert!(tea.description.is_some(), "registry holds the description");
    }

    #[test]
    fn groups_agents_by_module_deterministically() {
        let reg = read(&repo_root()).unwrap();
        let bmm = agents_for_module(&reg, "bmm");
        assert!(
            bmm.len() >= 6,
            "bmm should register several agents, got {bmm:?}"
        );
        let mut sorted = bmm.clone();
        sorted.sort();
        assert_eq!(bmm, sorted, "ordering must be deterministic");

        assert_eq!(agents_for_module(&reg, "tea"), vec!["bmad-tea"]);
        assert!(agents_for_module(&reg, "no-such-module").is_empty());
    }

    #[test]
    fn lists_modules_without_duplicates() {
        let reg = read(&repo_root()).unwrap();
        let m = modules(&reg);
        assert!(m.contains(&"bmm".to_string()));
        assert!(m.contains(&"tea".to_string()));
        let mut d = m.clone();
        d.dedup();
        assert_eq!(m, d);
    }

    #[test]
    fn surfaces_agent_blocks_the_registry_does_not_list() {
        // bmad-agent-builder ships an [agent] block with no identity fields. It must be
        // reported, not compiled, and not silently ignored (AD-6).
        let reg = read(&repo_root()).unwrap();
        let extra = unregistered_agent_blocks(&repo_root(), ".claude/skills", &reg);
        assert!(
            extra.contains(&"bmad-agent-builder".to_string()),
            "expected the builder skill to be surfaced, got {extra:?}"
        );
    }
}
